// @generated by gen-component — reproducible recipe:
//   prompt: "고요히 내리는 첫눈 — 천천히 흩날리며 떨어지는 작은 눈송이들, 잔잔하고 차분하게, 은은한 흰빛"
//   model:  claude-opus-4-8
//   at:     2026-06-05

// <FirstSnow count="90" color="#f4f8ff" sway="14"/>
// 고요히 내리는 첫눈 — small flakes drifting slowly down, swaying calm and soft.

import { Container, Graphics } from "pixi.js";
import type { RoomComponent, Prop, SceneUpdate } from "../types";
import { attr, int, opt, hex, num } from "../coerce";

interface FirstSnowProp extends Prop {
  type: "firstSnow";
  count: number;
  color?: number;
  sway?: number;
}

const FirstSnow: RoomComponent = {
  tag: "FirstSnow",
  type: "firstSnow",
  parse: (el): FirstSnowProp => ({
    type: "firstSnow",
    count: int(attr(el, "count")),
    color: opt(el, "color", hex, undefined),
    sway: opt(el, "sway", num, undefined),
  }),
  mount: (prop, { container, w, h, rng }): SceneUpdate => {
    const p = prop as FirstSnowProp;
    const color = p.color ?? 0xf4f8ff;
    const sway = p.sway ?? 14;

    const layer = new Container();
    container.addChild(layer);

    const flakes: {
      g: Container;
      x: number;
      y: number;
      r: number;
      fall: number;
      phase: number;
      swaySpeed: number;
      swayAmt: number;
    }[] = [];

    for (let i = 0; i < p.count; i++) {
      const r = 0.8 + rng() * 1.8;
      const g = new Container();
      g.addChild(new Graphics().circle(0, 0, r * 2.2).fill({ color, alpha: 0.06 }));
      g.addChild(new Graphics().circle(0, 0, r).fill({ color, alpha: 0.7 }));
      g.x = rng() * w;
      g.y = rng() * h;
      // smaller flakes fall slower (depth illusion)
      const depth = r / 2.6;
      g.alpha = 0.4 + depth * 0.5;
      layer.addChild(g);
      flakes.push({
        g,
        x: g.x,
        y: g.y,
        r,
        fall: (8 + depth * 18) * 0.001,
        phase: rng() * Math.PI * 2,
        swaySpeed: 0.0004 + rng() * 0.0007,
        swayAmt: sway * (0.5 + depth),
      });
    }

    return (dtMs, vw, vh) => {
      for (const f of flakes) {
        f.y += f.fall * dtMs;
        f.phase += f.swaySpeed * dtMs;
        if (f.y > vh + 6) {
          f.y = -6;
        }
        if (f.x > vw + 6) f.x -= vw + 12;
        if (f.x < -6) f.x += vw + 12;
        f.g.x = f.x + Math.sin(f.phase) * f.swayAmt;
        f.g.y = f.y;
      }
    };
  },
  example: { type: "firstSnow", count: 90, sway: 14 } as FirstSnowProp,
};

export default FirstSnow;
