// @generated by gen-component — reproducible recipe:
//   prompt: "조용한 밤비 — 가늘고 살짝 비스듬히 빠르게 내리는 빗줄기, 멀고 가까운 깊이감, 차분하고 lo-fi한 분위기"
//   model:  claude-opus-4-8
//   at:     2026-06-05

// <NightRain count="120" tilt="0.18" color="#9fb4d6"/>
// Thin, slightly-slanted rain streaks falling fast, with far/near depth layers
// for a quiet, lo-fi night mood.

import { Graphics } from "pixi.js";
import type { RoomComponent, Prop, SceneUpdate } from "../types";
import { attr, int, opt, num, hex } from "../coerce";

interface NightRainProp extends Prop {
  type: "nightRain";
  count: number;
  tilt: number; // horizontal lean as fraction of fall (0 = vertical)
  color: number;
}

interface Drop {
  g: Graphics;
  x: number;
  y: number;
  len: number;
  speed: number;
  depth: number; // 0 far .. 1 near
}

const NightRain: RoomComponent = {
  tag: "NightRain",
  type: "nightRain",
  parse: (el): NightRainProp => ({
    type: "nightRain",
    count: int(attr(el, "count")),
    tilt: opt(el, "tilt", num, 0.18),
    color: opt(el, "color", hex, 0x9fb4d6),
  }),
  mount: (prop, { container, w, h, rng }): SceneUpdate => {
    const p = prop as NightRainProp;
    const drops: Drop[] = [];

    for (let i = 0; i < p.count; i++) {
      const depth = rng(); // far..near
      const len = 8 + depth * 18;
      const thickness = 0.5 + depth * 1.1;
      const alpha = 0.12 + depth * 0.33;

      const g = new Graphics()
        .moveTo(0, 0)
        .lineTo(-p.tilt * len, len)
        .stroke({ color: p.color, width: thickness, alpha });

      g.x = rng() * (w * (1 + p.tilt));
      g.y = rng() * h;

      container.addChild(g);
      drops.push({
        g,
        x: g.x,
        y: g.y,
        len,
        speed: 0.55 + depth * 1.4,
        depth,
      });
    }

    return (dtMs, vw, vh) => {
      for (const d of drops) {
        const dy = d.speed * dtMs;
        d.y += dy;
        d.x -= dy * p.tilt;
        if (d.y > vh + d.len) {
          d.y = -d.len - rng() * vh * 0.3;
          d.x = rng() * (vw * (1 + p.tilt));
        } else if (d.x < -vw * p.tilt) {
          d.x += vw * (1 + p.tilt);
        }
        d.g.x = d.x;
        d.g.y = d.y;
      }
    };
  },
  example: { type: "nightRain", count: 120, tilt: 0.18, color: 0x9fb4d6 } as NightRainProp,
};

export default NightRain;
